apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "minijournal.fullname" . }}
  labels:
    {{- include "minijournal.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "minijournal.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "minijournal.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "minijournal.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-server
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.images.server.repository }}:{{ .Values.images.server.tag }}"
          imagePullPolicy: {{ .Values.images.server.pullPolicy }}
          ports:
            - name: websocket
              containerPort: {{ .Values.server_ws_port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "minijournal.fullname" . }}-env
            - secretRef:
                name: {{ include "minijournal.fullname" . }}-secret
        - name: {{ .Chart.Name }}-client
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.images.client.repository }}:{{ .Values.images.client.tag }}"
          imagePullPolicy: {{ .Values.images.client.pullPolicy }}
          ports:
            - name: nginx
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: nginx
          readinessProbe:
            httpGet:
              path: /
              port: nginx
          envFrom:
            - configMapRef:
                name: {{ include "minijournal.fullname" . }}-env
            - secretRef:
                name: {{ include "minijournal.fullname" . }}-secret
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
