apiVersion: v1
kind: Secret
metadata:
  name: {{ template "bot.fullname" . }}-secret
  labels:
    {{- include "bot.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.envSecrets }}
    {{ $key | quote  }}: {{ $value | quote }}
  {{- end }}
