apiVersion: v1
kind: Service
metadata:
  name: {{ include "minijournal.fullname" . }}-frontend
  labels:
    {{- include "minijournal.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.client.type }}
  ports:
    - port: {{ .Values.service.client.port }}
      targetPort: nginx
      protocol: TCP
      name: frontend
  selector:
    {{- include "minijournal.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "minijournal.fullname" . }}-server
  labels:
    {{- include "minijournal.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.client.type }}
  ports:
    - port: {{ .Values.service.client.port }}
      targetPort: websocket
      protocol: TCP
      name: server-ws
  selector:
    {{- include "minijournal.selectorLabels" . | nindent 4 }}
