apiVersion: v1
kind: Service
metadata:
  name: {{ include "minijournal.fullname" . }}
  labels:
    {{- include "minijournal.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: nginx
      protocol: TCP
      name: http
  selector:
    {{- include "minijournal.selectorLabels" . | nindent 4 }}
