replicaCount: 1

images:
  server:
    repository: ghcr.io/shanginn/minijournal-server
    pullPolicy: Always
    tag: "latest"
  client:
    repository: ghcr.io/shanginn/minijournal-client
    pullPolicy: Always
    tag: "latest"

server_ws_port: 3333
service:
  client:
    type: ClusterIP
    port: 30080

ingress:
  enabled: true
  annotations:
    cert-manager.io/issuer-kind: ClusterIssuer
    cert-manager.io/issuer: letsencrypt-prod
  hosts:
    - xn--b1abcbftdmxceabz.xn--p1ai
  tls:
    - secretName: minijournal-tls
      hosts:
        - xn--b1abcbftdmxceabz.xn--p1ai

serviceAccount:
  create: true
  name: "minijournal"

env:
  POSTGRES_HOST: pgsql-postgresql.pgsql
  POSTGRES_PORT: 5432
  POSTGRES_DB: minijournal
  POSTGRES_USER: minijournal

envSecrets:
  POSTGRES_PASSWORD: ""
