name: Build and Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build and push Docker images to GitHub Container Registry
    runs-on: ubuntu-latest
    permissions: write-all
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./client/Dockerfile
            image_for: client
            context: ./client
          - dockerfile: ./server/Dockerfile
            image_for: server
            context: ./server

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Convert repository name to lowercase
        run: echo "REPO_NAME=$(echo ${{ github.repository }} | awk -F '/' '{print tolower($2)}')" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          file: ${{ matrix.dockerfile }}
          context: ${{ matrix.context }}
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ env.REPO_NAME }}-${{ matrix.image_for }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Save Kube Config
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          mkdir -p ~/.kube/
          echo "${KUBECONFIG}" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Deploy app
        run: |
          cd helm
          helm upgrade minijournal --namespace=minijournal -f values.yaml . \
            --set=envSecrets.POSTGRES_PASSWORD="${POSTGRES_PASSWORD}"
          kubectl rollout restart deployment --namespace=minijournal